# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f2a6b23082f2bca382d34a142485d001fc7c52c84a5cb06061778c67977df8c7bc02d78c10f3210e83d2cf4da08151f6a8c83a0ce99d14c72fd363854a07b26

test:
  secret_key_base: 74d7b477e7465b6f62e752435646a568220c139031f4a9cd2a4bb2b1fb3ae13503ac53c1317d692fcf1c1c383385d411d914077372ce09b3b1e01a43b447c618

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
