class AddDefaultData < ActiveRecord::Migration[5.0]
  def up
    Admin.create(name: 'Administrador Anflei', username: 'anfeli', password: '8HjZ6wx7g9wa86LBM29qp2Z9Q')
    Admin.create(name: 'Administrador Prive', username: 'admin', password: 'R6m78sXRtJGU4jA222wh8b8f3')
    
    Information.create(key: 'youtube', value: 'www.youtube.com/playlist?list=PLd8wa7gwcPbpEQwr6Wt2gz14BIZ5MqoqJ')
    Information.create(key: 'phone-global', value: '0800 627575')
    Information.create(key: 'facebook-global', value: '')
    Information.create(key: 'instagram-global', value: '')
    Information.create(key: 'website-global', value: '')
    Information.create(key: 'contato-email-global', value: '')

    Information.create(key: 'pensao-tipo', value: 'Café da manhã')
    Information.create(key: 'pensao-tipo', value: 'Meia pensão (café e almoço)')
    Information.create(key: 'pensao-tipo', value: 'Pensão completa (café da manhã, almoço e jantar)')

    Information.create(key: 'hoteis-nome', value: 'Prive Riviera Park Hotel')
    Information.create(key: 'hoteis-nome', value: 'Prive Boulevard Suite Hotel')
    Information.create(key: 'hoteis-nome', value: 'Prive Termas Hotel')
    Information.create(key: 'hoteis-nome', value: 'Prive Marina Flat e Náutica')
    Information.create(key: 'hoteis-nome', value: 'Prive Atrium Thermas Residence Service')
    Information.create(key: 'hoteis-nome', value: 'Prive Náutico Flat Service')

    Information.create(key: 'programacao-title-global', value: 'Programação')
    Information.create(key: 'gastronomia-title-global', value: '')
    Information.create(key: 'promocoes-title-global', value: '')
    
    Parceiro.create(name: 'WATER PARK', telefone: '', site: 'https://www.google.com.br/maps/place/Water+Park/@-17.739401,-48.629405,15z/data=!4m2!3m1!1s0x0:0xc262a2cd9764b7e1?sa=X&ved=0ahUKEwjuwvHhjI7TAhUFhpAKHYcsC6cQ_BIIiwEwCg', longitude: -48.629405, latitude: -17.739401 , descricaoMapa: 'Sem descrição', descricao1: 'Sem descrição completa.', descricao2: 'Sem descrição à esquerda.', descricao3: 'Sem descrição à direita.', imagem: 'https://placeholdit.imgix.net/~text?txtsize=42&bg=ffffff&txtclr=000000&txt=Sem+imagem&w=320&h=480&txttrack=1', instagram: '', facebook: '')
    Parceiro.create(name: 'CLUBE PRIVE', telefone: '', site: 'https://www.google.com.br/maps/place/Clube+Priv%C3%A9/@-17.7390191,-48.630279,15z/data=!4m2!3m1!1s0x0:0xdd1c624791b691a9?sa=X&ved=0ahUKEwi1tqfcjY7TAhXDjJAKHchXD8gQ_BIIdDAK', longitude: -48.630279, latitude: -17.7390191, descricaoMapa: 'Sem descrição', descricao1: 'Sem descrição completa.', descricao2: 'Sem descrição à esquerda.', descricao3: 'Sem descrição a direita.', imagem: 'https://placeholdit.imgix.net/~text?txtsize=42&bg=ffffff&txtclr=000000&txt=Sem+imagem&w=320&h=480&txttrack=1', instagram: '', facebook: '')
    Parceiro.create(name: 'NAUTICO PRAIA CLUBE', telefone: '', site: 'https://www.google.com.br/maps/place/N%C3%A1utico+Praia+Clube/@-17.775957,-48.569767,15z/data=!4m2!3m1!1s0x0:0x64c0193baeffbdb9?sa=X&ved=0ahUKEwji983ojY7TAhXHTJAKHZr-CuoQ_BIIlAEwDg', longitude: -48.569767, latitude: -17.775957, descricaoMapa: 'Sem descrição', descricao1: 'Sem descrição completa.', descricao2: 'Sem descrição à esquerda.', descricao3: 'Sem descrição a direita.', imagem: 'https://placeholdit.imgix.net/~text?txtsize=42&bg=ffffff&txtclr=000000&txt=Sem+imagem&w=320&h=480&txttrack=1', instagram: '', facebook: '')
    Parceiro.create(name: 'PRIVE RIVIERA PARK HOTEL', telefone: '', site: 'https://www.google.com.br/maps/place/Prive+Riviera+Park+Hotel/@-17.739467,-48.63093,15z/data=!4m2!3m1!1s0x0:0x477a628957bc71ec?sa=X&ved=0ahUKEwi31vKHj47TAhUEvJAKHQn2DEoQ_BIIcjAK', longitude: -48.63093, latitude: -17.739467, descricaoMapa: 'O maior hotel de águas termais do Brasil com a qualidade Prive Hotéis & Parques, pertinho do centro de Caldas Novas e na região mais nobre da cidade.', descricao1: 'O maior hotel de águas termais do Brasil com a qualidade Prive Hotéis & Parques, pertinho do centro de Caldas Novas e na região mais nobre da cidade.', descricao2: 'Apartamentos Luxo:\n1 quarto com cama de casal e sofá-cama na sala que acomoda confortavelmente 2 adultos; Ar condicionado no quarto e TV LED a cabo, micro-ondas e frigobar.', descricao3: 'Apartamentos Família:\n1 Suíte com cama de casal e 1 quarto com 2 camas de solteiro e banheiro social. Sala com sofá-cama que acomoda confortavelmente 2 adultos. Ar-condicionado e TV LED a cabo no quarto de casal. Ar-condicionado em ambos os quartos. TV Led a cabo na sala, micro-ondas e frigobar.', imagem: 'https://placeholdit.imgix.net/~text?txtsize=42&bg=ffffff&txtclr=000000&txt=Sem+imagem&w=320&h=480&txttrack=1', instagram: '', facebook: '')
    Parceiro.create(name: 'PRIVE ATRIUM THERMAS RESIDENCE SERVICE', telefone: '', site: '', longitude: -48.6324721, latitude: -17.7411643, descricaoMapa: 'O conforto e a qualidade Prive Hotéis & Parques, pertinho do centro de Caldas Novas e na região mais nobre da cidade.', descricao1: 'O conforto e a qualidade Prive Hotéis & Parques, pertinho do centro de Caldas Novas e na região mais nobre da cidade.', descricao2: 'Apartamento\n1 quarto com cama de casal  e  cama auxiliar ; Sala com sofá-cama que acomoda confortavelmente 2 pessoas. Ar condicionado e TV LED a cabo no quarto e na sala, micro-ondas e frigobar.', descricao3: '', imagem: 'https://placeholdit.imgix.net/~text?txtsize=42&bg=ffffff&txtclr=000000&txt=Sem+imagem&w=320&h=480&txttrack=1', instagram: '', facebook: '')
    Parceiro.create(name: 'PRIVE NAUTICO FLAT SERVICE', telefone: '', site: 'https://www.google.com.br/maps/place/N%C3%A1utico+flat/@-17.7742567,-48.5685306,15z/data=!4m2!3m1!1s0x0:0xd5cd0e38a75632f3?sa=X&ved=0ahUKEwi72Pnyjo7TAhXLiJAKHVddAoMQ_BIIcjAK', longitude: -48.5685306, latitude: -17.7742567, descricaoMapa: 'Situado no belo Lago Corumbá, é a opção ideal para quem busca economia com a qualidade Prive Hotéis & Parques. Viva momentos de lazer e aventura na natureza.', descricao1: 'Situado no belo Lago Corumbá, é a opção ideal para quem busca economia com a qualidade Prive Hotéis & Parques. Viva momentos de lazer e aventura na natureza.', descricao2: 'Apartamento Standard:\nSala,  1 quarto, 1 banheiro social e sacada, sala com sofá-cama que acomoda confortavelmente 2 adultos, ar condicionado na sala e quarto, TV na sala.', descricao3: '', imagem: 'https://placeholdit.imgix.net/~text?txtsize=42&bg=ffffff&txtclr=000000&txt=Sem+imagem&w=320&h=480&txttrack=1', instagram: '', facebook: '')
    Parceiro.create(name: 'PRIVE MARINA FLAT & NAUTICA', telefone: '', site: 'https://www.google.com.br/maps/place/Prive+Marina+Flat+%26+N%C3%A1utica/@-17.7390816,-48.6302482,15z/data=!4m2!3m1!1s0x0:0x56680f268c6bcaa8?sa=X&ved=0ahUKEwjonOrpjo7TAhVFh5AKHdDECcMQ_BIIcDAK', longitude: -48.6302482, latitude: -17.7390816, descricaoMapa: 'Respire novos ares e cerque-se de natureza por todos os lados com o conforto Prive Hotéis & Parques, viva momentos únicos às margens do Lago Corumbá em Caldas Novas.', descricao1: 'Respire novos ares e cerque-se de natureza por todos os lados com o conforto Prive Hotéis & Parques, viva momentos únicos às margens do Lago Corumbá em Caldas Novas.', descricao2: 'Apartamentos Família:\n1 suíte com uma cama casal, um banheiro social, um quarto com duas camas de solteiro, sala com sofá-cama que acomoda confortavelmente 2 adultos. Ar-condicionado na suíte, no quarto e na sala, frigobar, armários e TV LED na sala.', descricao3: 'Apartamentos Standard:\n1 Quarto com 1 cama de casal no quarto e um sofá-cama na sala que acomoda confortavelmente 2 adultos, ar condicionado na sala e no quarto. Frigobar, armários e TV LED na sala.', imagem: 'https://placeholdit.imgix.net/~text?txtsize=42&bg=ffffff&txtclr=000000&txt=Sem+imagem&w=320&h=480&txttrack=1', instagram: '', facebook: '')
    Parceiro.create(name: 'PRIVE BOULEVARD SUITE HOTEL', telefone: '', site: 'https://www.google.com.br/maps/place/Prive+Boulevard+Suite+Hotel/@-17.7378276,-48.629687,15z/data=!4m2!3m1!1s0x0:0xd77337b6e17ff95a?sa=X&ved=0ahUKEwiCnfXijo7TAhXKI5AKHV6bCkMQ_BIIdTAK', longitude: -48.629687, latitude: -17.7378276, descricaoMapa: 'Estrutura moderna e a qualidade Prive Hotéis & Parques, pertinho do centro de Caldas Novas e na região mais nobre da cidade.', descricao1: 'Estrutura moderna e a qualidade Prive Hotéis & Parques, pertinho do centro de Caldas Novas e na região mais nobre da cidade.', descricao2: 'Apartamentos Luxo:\n1 cama de casal ou 2 camas de solteiro, sala com 1 sofá-cama que acomoda confortavelmente até 2 adultos. Ar-condicionado e TV LED com sinal de parabólica, micro-ondas e frigobar.', descricao3: 'Apartamentos Superluxo:\n1 cama de casal ou 2 camas de solteiro, sala com 1 sofá-cama que acomoda 2 crianças até 12 anos e sacada. Ar-condicionado  e TV LED  com sinal de parabólica nos dois ambientes, micro-ondas e frigobar.', imagem: 'https://placeholdit.imgix.net/~text?txtsize=42&bg=ffffff&txtclr=000000&txt=Sem+imagem&w=320&h=480&txttrack=1', instagram: '', facebook: '')
    Parceiro.create(name: 'PRIVE THERMAS HOTEL', telefone: '', site: 'https://www.google.com.br/maps/place/Prive+Thermas+Hotel/@-17.738472,-48.629479,15z/data=!4m5!3m4!1s0x0:0x9e5a98cf62be4c8b!8m2!3d-17.738472!4d-48.629479', longitude: -48.629479, latitude: -17.738472, descricaoMapa: 'Tradição e modernidade com a qualidade Prive Hotéis & Parques, desfrute de momentos inesquecíveis em meio à muito verde e piscinas quentinhas.', descricao1: 'Tradição e modernidade com a qualidade Prive Hotéis & Parques, desfrute de momentos inesquecíveis em meio à muito verde e piscinas quentinhas.', descricao2: 'Apartamentos Standard\n1 cama de casal e 2 camas de solteiro ou 1 cama de casal e 1 de solteiro, ar-condicionado, TV a cabo e frigobar.', descricao3: 'Apartamentos Luxo\n1 cama de casal e uma cama de solteiro ou três camas de solteiro, ar-condicionado, Tv a cabo e frigobar.', imagem: 'https://placeholdit.imgix.net/~text?txtsize=42&bg=ffffff&txtclr=000000&txt=Sem+imagem&w=320&h=480&txttrack=1', instagram: '', facebook: '')
    Parceiro.create(name: 'Choperia Boulevard', telefone: '', site: 'https://www.google.com.br/maps/place/Boulevard+Choperia+%26+Restaurante/@-17.7378955,-48.6299128,15z/data=!4m2!3m1!1s0x0:0xa89db36de802b7bf?sa=X&ved=0ahUKEwjxsP-kj47TAhWEgpAKHZ5oCEEQ_BIIfDAP', longitude: -48.629479, latitude: -17.738472, descricaoMapa: 'A Chopperia Boulevard é simplesmente "o" point de Caldas Novas. Com um ambiente ao mesmo descontraído e requintado, é ideal para levar os amigos para tomar um Chopp estupidamente gelado com um cardápio delicioso, inspirado na cozinha goiana com um toque gourmet. Localizado na área nobre de Caldas Novas, é anexo ao Privé Boulevard Suite Hotel, dentro do quadrilátero turístico da Rede Privé. Quando vier a Caldas Novas, venha se refrescar com o melhor Chopp da região das Águas quentes.', descricao1: 'A Chopperia Boulevard é simplesmente "o" point de Caldas Novas. Com um ambiente ao mesmo descontraído e requintado, é ideal para levar os amigos para tomar um Chopp estupidamente gelado com um cardápio delicioso, inspirado na cozinha goiana com um toque gourmet. Localizado na área nobre de Caldas Novas, é anexo ao Privé Boulevard Suite Hotel, dentro do quadrilátero turístico da Rede Privé. Quando vier a Caldas Novas, venha se refrescar com o melhor Chopp da região das Águas quentes.', descricao2: '', descricao3: '', imagem: 'https://cdn.prive.anfeli.com.br/images/parceiros/logo.choperia.png', instagram: '', facebook: '')
    Parceiro.create(name: 'Pizzaria Firenze', telefone: '', site: 'https://www.google.com.br/maps/place/Firenze+Pizzaria/@-17.7379142,-48.6292722,15z/data=!4m2!3m1!1s0x0:0xb23add10697e5605?sa=X&ved=0ahUKEwis5sy7j47TAhXIlJAKHTS3DMAQ_BIIdDAK', longitude: -48.6292722, latitude: -17.7379142, descricaoMapa: 'Para você que gosta de saborear uma deliciosa pizza, vai aqui a dica! Pizzaria Firenze, Bouna gente! A pizzaria Firenze é uma fatia da Itália no coração do Brasil. As pizzas são feitas com ingredientes frescos, selecionados, dentro do mais alto rigor da tradição italiana. O que está esperando, ragazzo? Quando vier a Caldas Novas, não deixe de experimentar as delícias da Pizzaria Firenze. Anexa ao Privé Boulevard Suite Hotel.', descricao1: 'Para você que gosta de saborear uma deliciosa pizza, vai aqui a dica! Pizzaria Firenze, Bouna gente! A pizzaria Firenze é uma fatia da Itália no coração do Brasil. As pizzas são feitas com ingredientes frescos, selecionados, dentro do mais alto rigor da tradição italiana. O que está esperando, ragazzo? Quando vier a Caldas Novas, não deixe de experimentar as delícias da Pizzaria Firenze. Anexa ao Privé Boulevard Suite Hotel.', descricao2: '', descricao3: '', imagem: 'https://cdn.prive.anfeli.com.br/images/parceiros/logo.pizzaria.png', instagram: '', facebook: '')
    
    fidelidade = Gallery.create(category: 'fidelidade', title: '')
    fidelidade.images.create(url: 'https://cdn.prive.anfeli.com.br/images/fidelidade/1491230257_Cupons1.jpg')
    fidelidade.images.create(url: 'https://cdn.prive.anfeli.com.br/images/fidelidade/1491230257_Cupons2.jpg')
    fidelidade.images.create(url: 'https://cdn.prive.anfeli.com.br/images/fidelidade/1491230257_Cupons3.jpg')
    
    hotel = Gallery.create(category: 'hotel', title: 'PRIVE ATRIUM THERMAS RESIDENCE SERVICE')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-atrium-thermas-residence-service/atrium-fachada-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-atrium-thermas-residence-service/atrium-fachada-02.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-atrium-thermas-residence-service/atrium-parque-aquatico-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-atrium-thermas-residence-service/atrium-parque-aquatico-02.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-atrium-thermas-residence-service/atrium-parque-aquatico-03.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-atrium-thermas-residence-service/atrium-parque-aquatico-05.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-atrium-thermas-residence-service/atrium-recepcao-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-atrium-thermas-residence-service/atrium-recepcao-02.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-atrium-thermas-residence-service/atrium-restaurante-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-atrium-thermas-residence-service/atrium-restaurante-02.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-atrium-thermas-residence-service/Prive-Atrium-Thermas-Residence-e-Service.jpg')

    hotel = Gallery.create(category: 'hotel', title: 'PRIVE BOULEVARD SUITE HOTEL')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/2POL6225.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/2POL6251.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/2POL6295.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/2POL6311.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/prive-boulevard-aerea-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/prive-boulevard-aerea-02.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/prive-boulevard-aerea-03.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/prive-boulevard-alimentacao-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/prive-boulevard-alimentacao-03.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/prive-boulevard-fachada-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/prive-boulevard-fachada-02.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/prive-boulevard-lazer-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/prive-boulevard-lazer-02.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-boulevard-suite-hotel/prive-boulevard-recepcao.jpg')

    hotel = Gallery.create(category: 'hotel', title: 'PRIVE THERMAS HOTEL')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/2POL6337.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/2POL6403.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/2POL6408.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/2POL6422_1.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/hotel-prive-apto-04.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/hotel-prive-apto-06.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/hotel-prive-bar-molhado.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/hotel-prive-parque-aquatico-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/hotel-prive-parque-aquatico-03.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/hotel-prive-parque-aquatico-04.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/hotel-prive-parque-aquatico-05.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/hotel-prive-parque-aquatico-06.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/hotel-prive-parque-aquatico-07.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/hotel-prive-parque-aquatico-08.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/hotel-prive-parque-aquatico-09.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/hotel-prive-parque-aquatico-10.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/Prive-Thermas-Hotel-2.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/Prive-Thermas-Hotel-3.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/Prive-Thermas-Hotel-4.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-thermas-hotel/Prive-Thermas-Hotel.jpg')

    hotel = Gallery.create(category: 'hotel', title: 'PRIVE MARINA FLAT & NAUTICA')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/2POL6829.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/2POL6864.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/2POL6872.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/2POL6892.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/2POL6943.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/marina-flat-apto1505-standart-02.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/marina-flat-apto1505-standart-04.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/marina-flat-fachada.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/marina-flat-piscina-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/marina-flat-piscina-02.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/marina-flat-piscina-03.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/marina-flat-piscina-04.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/marina-flat-piscina-05.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-marina-flat-nautica/marina-flat-piscina.jpg')


    hotel = Gallery.create(category: 'hotel', title: 'PRIVE NAUTICO FLAT SERVICE')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-nautico-flat-service/nautico-flat-apto204b-standart-04.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-nautico-flat-service/nautico-flat-apto204b-standart-05.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-nautico-flat-service/nautico-flat-apto204b-standart-06.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-nautico-flat-service/nautico-flat-fachada-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-nautico-flat-service/nautico-flat-fachada-03.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-nautico-flat-service/nautico-flat-fachada-04.jpg')

    hotel = Gallery.create(category: 'hotel', title: 'PRIVE RIVIERA PARK HOTEL')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/2POL6468.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/2POL6561.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/2POL6573.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/2POL6627.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/2POL6907.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/2POL6925.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/2POL6937.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/_MLK2321.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/_MLK2337-ok.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/_MLK2365-ok.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/DJI_0117.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/hotel-prive-apto-03.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/IMG_6204.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/IMG_9493.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/IMG_9757.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/Prive-Hoteis-e-Parques---Casal-03.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-academia-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-academia-02.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-aerea-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-apto666-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-apto666-05.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-apto666-09.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-apto666-12.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-fachada.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-lazer-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-lazer-02.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-lazer-03.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-recepcao-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-recepcao-02.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/prive-riviera-restaurante-01.jpg')
    hotel.images.create(url: 'https://cdn.prive.anfeli.com.br/images/prive-riviera-park-hotel/riviera1.jpg')
    
    Novidade.create(name: 'ABRIL – CULINÁRIA NORDESTINA', descricao: "Terças-Feiras\n\nLocal: Restaurantes do hotéis do Prive Hotéis &amp; Parques\nHorário: das 19h às 22h\n\nSextas-feiras\n\nLocal: Restaurantes dos hotéis do Prive Hotéis &amp; Parques\nHorário: das 19h às 22h", categoria: 'gastronomia')
    Novidade.create(name: 'MAIO – CULINÁRIA PORTUGUESA', descricao: "Terças-Feiras\n\nLocal: Restaurantes do hotéis do Prive Hotéis &amp; Parques\nHorário: das 19h às 22h\n\nSextas-feiras\n\nLocal: Restaurantes dos hotéis do Prive Hotéis &amp; Parques\nHorário: das 19h às 22h", categoria: 'gastronomia')
    Novidade.create(name: 'JUNHO - CULINÁRIA ESPANHOLA', descricao: "Terças-Feiras\n\nLocal: Restaurantes do hotéis do Prive Hotéis &amp; Parques\nHorário: das 19h às 22h\n\nSextas-feiras\n\nLocal: Restaurantes dos hotéis do Prive Hotéis &amp; Parques\n\nHorário: das 19h às 22h", categoria: 'gastronomia')
    
    Novidade.create(name: 'FERIADO DIA DO TRABALHADOR', descricao: 'O trabalho enobrece o homem, mas uma folguinha aqui no Prive Hotéis & Parques cai muito bem! Curta o descanso que você merece, com acesso aos 3 melhores parques aquáticos de Caldas Novas. Diárias a partir de R$585,00*. Consulte condições no nosso site. Garanta sua reserva!', categoria: 'promocao')
    Novidade.create(name: 'FERIADO DE TIRADENTES', descricao: "DIVERSÃO À VISTA!\nFeriado na piscina é ideal para descansar, não acha? E, para ficar ainda melhor, que tal piscinas naturalmente quentes? No Prive Hotéis & Parques você tem tudo isso, além do acesso aos 3 melhores parques aquáticos de Caldas Novas.  Diárias a partir de R$585,00*. Consulte condições no nosso site. Garanta sua reserva!", categoria: 'promocao')
    Novidade.create(name: 'FERIADO DE PÁSCOA', descricao: "UMA PÁSCOA MAIS DOCE NO PRIVE HOTÉIS & PARQUES!\nAqui você e sua família aproveitam o feriado de Páscoa com todo conforto, na melhor rede de hotéis de Caldas Novas, e acesso aos 3 melhores parques aquáticos da cidade. Diárias a partir de R$ 1.153,00*. Consulte condições no nosso site. Garanta sua reserva!", categoria: 'promocao')
  end
  
  def down
    
  end
end
